#!/usr/bin/env python3
"""Create an RMBLAST_DIR shim that injects ``-culling_limit N`` into rmblastn
and pins it to ``-num_threads 1`` for deterministic culling.

RepeatMasker resolves both ``rmblastn`` and ``makeblastdb`` from its
``RMBLAST_DIR``, which it reads from the environment (RepeatMaskerConfig.pm).
There is no CLI flag to add extra rmblastn parameters, so we build a tiny shim
directory whose ``rmblastn`` rewrites real search invocations (those carrying
``-query``; ``-version`` and friends pass through untouched) to append
``-culling_limit N`` and force ``-num_threads 1``, plus a symlink to the real
``makeblastdb``, and point ``RMBLAST_DIR`` at it. This injects culling with NO
RepeatMasker/container patch and works for any tool that drives RepeatMasker's
ncbi engine — the main ``repeatmasker`` rule (via repeatmasker_wrapper.py) and
TideCluster's ``tc_reannotate.py`` (which inherits ``RMBLAST_DIR`` from the
``tidecluster_reannotate`` rule shell). So both RepeatMasker layers get culling
AND determinism from this one helper — TideCluster itself is not patched.

``-culling_limit N`` discards an HSP whose query range is enveloped by >= N
higher-scoring HSPs. It collapses redundant HSPs at search time: per-locus
library-variant redundancy (many near-identical consensi) and, for tandem-array
reannotation, the phase-shifted overlapping hits a dimer consensus makes at every
rotational offset. The best hit per locus is never culled, so masking and
classification are preserved.

**Why ``-num_threads 1``:** NCBI BLAST culling is non-deterministic across
threads — each worker collects HSPs, they are merged in completion order, and
``-culling_limit`` then drops equal-scoring enveloped HSPs in that order.
RepeatMasker launches rmblastn with ``-num_threads 4`` even at ``-pa 1``, so
culling ON produced run-to-run differences (a handful of boundary / tied
sub-consensus / divergence jitters per 10^5 hits). Pinning threads to 1 makes
culling bit-reproducible; parallelism is recovered at the chunk level (the
wrapper's ``multiprocessing.Pool`` and TideCluster's ``--chunk_size``), so
throughput is preserved — and on large genomes it also removes the
16-workers x 4-threads CPU oversubscription. Culling OFF is already
deterministic (no shim is built), so this pin only matters when culling is on.

As a library:  make_culling_shim(culling_limit, parent_dir) -> shim_dir or None.
As a CLI: prints the shim dir to stdout (nothing if off / rmblastn missing), so a
shell rule can do:
    shim=$(rmblast_culling_shim.py -n 2 -d "$PWD")
    [ -n "$shim" ] && export RMBLAST_DIR="$shim"
"""
import argparse
import os
import shutil
import sys


def make_culling_shim(culling_limit, parent_dir):
    """Build the shim dir and return its path, or None if culling is off /
    rmblastn can't be located (callers then run unchanged — culling is an
    optimisation, never a correctness requirement)."""
    try:
        culling_limit = int(culling_limit)
    except (TypeError, ValueError):
        return None
    if culling_limit <= 0:
        return None
    real_rmblastn = shutil.which('rmblastn')
    if real_rmblastn is None:
        sys.stderr.write("rmblast_culling_shim: rmblastn not on PATH; "
                         "running WITHOUT culling.\n")
        return None
    real_dir = os.path.dirname(os.path.realpath(real_rmblastn))
    real_makeblastdb = shutil.which('makeblastdb') or os.path.join(real_dir,
                                                                   'makeblastdb')
    shim_dir = os.path.join(os.path.abspath(parent_dir), 'rmblast_culling_shim')
    os.makedirs(shim_dir, exist_ok=True)
    shim_makeblastdb = os.path.join(shim_dir, 'makeblastdb')
    if os.path.lexists(shim_makeblastdb):
        os.remove(shim_makeblastdb)
    os.symlink(real_makeblastdb, shim_makeblastdb)
    shim_rmblastn = os.path.join(shim_dir, 'rmblastn')
    with open(shim_rmblastn, 'w') as fh:
        fh.write(
            "#!/bin/bash\n"
            "# Auto-generated by rmblast_culling_shim.py. For real rmblastn searches\n"
            "# (those carrying -query; -version etc. pass through untouched) it (a)\n"
            "# appends -culling_limit N and (b) forces -num_threads 1, replacing any\n"
            "# -num_threads RepeatMasker supplied.\n"
            "#\n"
            "# Single-threaded is REQUIRED for determinism: NCBI BLAST culling is\n"
            "# non-deterministic across threads (each thread collects HSPs, they are\n"
            "# merged in completion order, then -culling_limit drops equal-scoring\n"
            "# enveloped HSPs in that order). RepeatMasker launches rmblastn with\n"
            "# -num_threads 4 even at -pa 1, so culling ON without this pin gives\n"
            "# different results run-to-run. Chunk-level parallelism (the wrapper's\n"
            "# multiprocessing.Pool / TideCluster's --chunk_size) preserves throughput.\n"
            'REAL="%s"\n'
            "args=()\n"
            "strip=0\n"
            "has_query=0\n"
            'for a in "$@"; do\n'
            '  if [ "$strip" = 1 ]; then strip=0; continue; fi\n'
            '  if [ "$a" = "-num_threads" ]; then strip=1; continue; fi\n'
            '  [ "$a" = "-query" ] && has_query=1\n'
            '  args+=("$a")\n'
            "done\n"
            'if [ "$has_query" = 1 ]; then\n'
            '  exec "$REAL" "${args[@]}" -num_threads 1 -culling_limit %d\n'
            "fi\n"
            'exec "$REAL" "${args[@]}"\n' % (real_rmblastn, culling_limit)
        )
    os.chmod(shim_rmblastn, 0o755)
    return shim_dir


def main():
    parser = argparse.ArgumentParser(
        description="Create an RMBLAST_DIR shim injecting rmblastn -culling_limit; "
                    "prints the shim dir (nothing if off/unavailable).")
    parser.add_argument('-n', '--culling-limit', dest='culling_limit', type=int,
                        default=0, help='rmblastn -culling_limit (0 = off)')
    parser.add_argument('-d', '--parent-dir', dest='parent_dir', default='.',
                        help='directory under which to create the shim')
    args = parser.parse_args()
    shim_dir = make_culling_shim(args.culling_limit, args.parent_dir)
    if shim_dir:
        print(shim_dir)


if __name__ == '__main__':
    main()
