#!/usr/bin/env python3
"""Create an RMBLAST_DIR shim that injects ``-culling_limit N`` into rmblastn.

RepeatMasker resolves both ``rmblastn`` and ``makeblastdb`` from its
``RMBLAST_DIR``, which it reads from the environment (RepeatMaskerConfig.pm).
There is no CLI flag to add extra rmblastn parameters, so we build a tiny shim
directory whose ``rmblastn`` appends ``-culling_limit N`` to real search
invocations (those carrying ``-query``; ``-version`` and friends pass through
untouched) plus a symlink to the real ``makeblastdb``, and point ``RMBLAST_DIR``
at it. This injects culling with NO RepeatMasker/container patch and works for
any tool that drives RepeatMasker's ncbi engine — the main ``repeatmasker`` rule
(via repeatmasker_wrapper.py) and TideCluster's ``tc_reannotate.py``.

``-culling_limit N`` discards an HSP whose query range is enveloped by >= N
higher-scoring HSPs. It collapses redundant HSPs at search time: per-locus
library-variant redundancy (many near-identical consensi) and, for tandem-array
reannotation, the phase-shifted overlapping hits a dimer consensus makes at every
rotational offset. The best hit per locus is never culled, so masking and
classification are preserved.

As a library:  make_culling_shim(culling_limit, parent_dir) -> shim_dir or None.
As a CLI: prints the shim dir to stdout (nothing if off / rmblastn missing), so a
shell rule can do:
    shim=$(rmblast_culling_shim.py -n 2 -d "$PWD")
    [ -n "$shim" ] && export RMBLAST_DIR="$shim"
"""
import argparse
import os
import shutil
import sys


def make_culling_shim(culling_limit, parent_dir):
    """Build the shim dir and return its path, or None if culling is off /
    rmblastn can't be located (callers then run unchanged — culling is an
    optimisation, never a correctness requirement)."""
    try:
        culling_limit = int(culling_limit)
    except (TypeError, ValueError):
        return None
    if culling_limit <= 0:
        return None
    real_rmblastn = shutil.which('rmblastn')
    if real_rmblastn is None:
        sys.stderr.write("rmblast_culling_shim: rmblastn not on PATH; "
                         "running WITHOUT culling.\n")
        return None
    real_dir = os.path.dirname(os.path.realpath(real_rmblastn))
    real_makeblastdb = shutil.which('makeblastdb') or os.path.join(real_dir,
                                                                   'makeblastdb')
    shim_dir = os.path.join(os.path.abspath(parent_dir), 'rmblast_culling_shim')
    os.makedirs(shim_dir, exist_ok=True)
    shim_makeblastdb = os.path.join(shim_dir, 'makeblastdb')
    if os.path.lexists(shim_makeblastdb):
        os.remove(shim_makeblastdb)
    os.symlink(real_makeblastdb, shim_makeblastdb)
    shim_rmblastn = os.path.join(shim_dir, 'rmblastn')
    with open(shim_rmblastn, 'w') as fh:
        fh.write(
            "#!/bin/bash\n"
            "# Auto-generated by rmblast_culling_shim.py; appends -culling_limit\n"
            "# to real rmblastn searches (passes -version etc. through).\n"
            'REAL="%s"\n'
            'for a in "$@"; do\n'
            '  if [ "$a" = "-query" ]; then\n'
            '    exec "$REAL" "$@" -culling_limit %d\n'
            '  fi\n'
            'done\n'
            'exec "$REAL" "$@"\n' % (real_rmblastn, culling_limit)
        )
    os.chmod(shim_rmblastn, 0o755)
    return shim_dir


def main():
    parser = argparse.ArgumentParser(
        description="Create an RMBLAST_DIR shim injecting rmblastn -culling_limit; "
                    "prints the shim dir (nothing if off/unavailable).")
    parser.add_argument('-n', '--culling-limit', dest='culling_limit', type=int,
                        default=0, help='rmblastn -culling_limit (0 = off)')
    parser.add_argument('-d', '--parent-dir', dest='parent_dir', default='.',
                        help='directory under which to create the shim')
    args = parser.parse_args()
    shim_dir = make_culling_shim(args.culling_limit, args.parent_dir)
    if shim_dir:
        print(shim_dir)


if __name__ == '__main__':
    main()
